### ISSUE TITLE
Set default view to be "all" (Maybe)

### ISSUE THREAD

**Issue by Googolplexic** [MACHI-NE/MACHI-NE-#56]

**Comment by Googolplexic** [comment]
as it doesn't get visible coords until map is panned

**Comment by Marcetho** [comment]
I think the panning issue has been fixed? Also based on testing with console.log inside refreshVisibleEvents, the visible events list is initially refreshed when the page loads for the first time. I think this is because the MainMap component initially calls setVisiblePoints, which triggers the visible points refresh in App.tsx.

**Comment by Googolplexic** [comment]
sweet, will close then
